### ISSUE TITLE
Does the PagerDuty plugin allow retrieval of pages?

### ISSUE THREAD

**Issue by achantavy** [rapid7/insightconnect-plugins#340]
Hi,
Does the InsightConnect PagerDuty plugin allow retrieval of pages?  I see in the [doc](https://github.com/rapid7/insightconnect-plugins/blob/master/pagerduty/help.md) that it can send acks but I don't see anything about listing events.

Thanks!

**Comment by jschipp-r7** [comment]
Hey @achantavy, it's not supported at this time but it's something that we can accept a contribution for or we can add given the nature of the request for it. It would need to be a trigger to the plugin that retrieves the latests events.

Let me know if you have any other questions.
