### ISSUE TITLE
New Plugin Request: Enrichment via GreyNoise

### ISSUE THREAD

**Issue by bradchiappetta** [rapid7/insightconnect-plugins#885]
### Description

We would like to contribute a new plugin that provides GreyNoise as an enrichment plugin to InsightConnect.  We will be submitting a PR with our initial efforts to contribute to this plugin.

The plugin will support interaction with the GreyNoise API (documented here: https://developer.greynoise.io/reference).

Included Actions will include:
- IP Context Lookup
- IP Quick Lookup
- IP RIOT Lookup
- Get Tag Metadata
- Perform a GNQL Query
- IP Lookup via Community API (for free users)

**Comment by jschipp-r7** [comment]
Plugin has been released https://extensions.rapid7.com/extension/greynoise

Thanks for the contribution!
