### ISSUE TITLE
EasyVista connection test not working as expected

### ISSUE THREAD

**Issue by jimmy-ack** [rapid7/insightconnect-plugins#959]
### Prerequisites

* [X] Are you running the latest version of [icon-plugin](https://docs.rapid7.com/insightconnect/getting-started/)?
* [X] Did you verify your credentials for the connection?
* [ ] Provide your plugin input in JSON
* [ ] Provide your plugin output in JSON
* [X] Provide any errors, stack traces, and logging messages

### Description

Connection test for EasyVista plugin not working.

### Steps to Reproduce

1. Create a new easyvista connection
2. Run a connection test

**Expected behavior:** A connection test should be ok if all settings are defined as expected. 

**Actual behavior:** 

When running a connection test we have the following error : 

````
Connect: Connecting... rapid7/EasyVista:1.0.0. Step name: close_ticket 'EasyVistaApi' object has no attribute 'search_ticket' Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.0-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 326, in handle_step output = self.start_step( File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.0-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 481, in start_step output = func() File "/usr/local/lib/python3.8/site-packages/easyvista_rapid7_plugin-1.0.0-py3.8.egg/icon_easyvista/connection/connection.py", line 20, in test self.client.search_ticket("submit_date_ut:today") AttributeError: 'EasyVistaApi' object has no attribute 'search_ticket'

````

After checking the code it seems there's an error in `search_ticket` method name.

Could you have a look on this part please ? 

Regards,

**Comment by jschipp-r7** [comment]
Thanks for reporting @jimmy-ack. We have filed this ticket internally and engineering will look into this.
For future tickets and requests we recommend contacting support or using our Discuss forums: https://discuss.rapid7.com/

**Comment by jschipp-r7** [comment]
@jimmy-ack We have released a new fix at https://extensions.rapid7.com/extension/easyvista/v1.0.1 

Let us know if you have any more difficulties or questions!
